-- ISIP Supabase schema
-- Run these in the Supabase SQL editor or via supabase db reset

-- Safety events: zone intrusions, PPE violations, relay trips, E-Stop
create table if not exists public.safety_events (
  id bigint generated by default as identity primary key,
  node_id text not null,
  event_type text not null,
  severity text not null,
  zone_id text,
  rule_id text,
  confidence double precision,
  payload jsonb not null default '{}'::jsonb,
  latency_ms double precision,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Audit trail mirror (in addition to local JSONL)
create table if not exists public.audit_entries (
  id bigint generated by default as identity primary key,
  node_id text not null,
  event_type text not null,
  severity text not null,
  latency_ms double precision,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Telemetry samples for long-term sensor history
create table if not exists public.telemetry_samples (
  id bigint generated by default as identity primary key,
  node_id text not null,
  sensor_id text not null,
  metric text not null,
  value double precision not null,
  unit text,
  status text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RUL updates for predictive maintenance tracking
create table if not exists public.rul_updates (
  id bigint generated by default as identity primary key,
  node_id text not null,
  sensor_id text not null,
  health_pct double precision not null,
  remaining_hours double precision not null,
  consumed_hours double precision not null,
  accumulated_damage double precision not null,
  status text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Inference performance monitoring
create table if not exists public.inference_events (
  id bigint generated by default as identity primary key,
  node_id text not null,
  latency_ms double precision not null,
  fps double precision not null,
  detections jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indexes for common query patterns
create index if not exists idx_safety_events_node_created on public.safety_events (node_id, created_at desc);
create index if not exists idx_audit_entries_node_created on public.audit_entries (node_id, created_at desc);
create index if not exists idx_telemetry_samples_node_sensor_created on public.telemetry_samples (node_id, sensor_id, created_at desc);
create index if not exists idx_rul_updates_node_sensor_created on public.rul_updates (node_id, sensor_id, created_at desc);
create index if not exists idx_inference_events_node_created on public.inference_events (node_id, created_at desc);

-- Enable Row Level Security (RLS) for production use
alter table public.safety_events enable row level security;
alter table public.audit_entries enable row level security;
alter table public.telemetry_samples enable row level security;
alter table public.rul_updates enable row level security;
alter table public.inference_events enable row level security;

-- Service role bypasses RLS (for edge node inserts)
create policy "service_role_insert_safety_events" on public.safety_events
  for insert using (auth.role() = 'service_role');
create policy "service_role_insert_audit_entries" on public.audit_entries
  for insert using (auth.role() = 'service_role');
create policy "service_role_insert_telemetry_samples" on public.telemetry_samples
  for insert using (auth.role() = 'service_role');
create policy "service_role_insert_rul_updates" on public.rul_updates
  for insert using (auth.role() = 'service_role');
create policy "service_role_insert_inference_events" on public.inference_events
  for insert using (auth.role() = 'service_role');

-- Allow public read for dashboard (adjust as needed)
create policy "public_read_safety_events" on public.safety_events
  for select using (true);
create policy "public_read_audit_entries" on public.audit_entries
  for select using (true);
create policy "public_read_telemetry_samples" on public.telemetry_samples
  for select using (true);
create policy "public_read_rul_updates" on public.rul_updates
  for select using (true);
create policy "public_read_inference_events" on public.inference_events
  for select using (true);
